sudo: false
dist: xenial
group: stable

language: scala
scala:
- 2.11.12
- 2.12.8

## add the following jobs to the build matrix:
matrix:
  include:
  - jdk: openjdk8
    before_install:
      - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
      - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
    apt:
      packages:
        - openjdk8
  - jdk: openjdk11
  - scala: 2.13.0-RC1
    script:
    # TODO enable test
    - sbt "++ ${TRAVIS_SCALA_VERSION}" "all argonaut/compile ast/compile json4s/compile parser/compile play/compile util/compile"

script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}" test

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
